GET http://127.0.0.1:8080/api/todos/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InRvZG9zIjpbXSwidG9kb19jb2xsZWN0aW9ucyI6W10sIl9pZCI6IjYwNTJjNTAwYzZkMzk5MWVlNGY0ZWQ2NyIsInVzZXJuYW1lIjoia2FkYWxzIiwicGFzc3dvcmQiOiIkMmEkMTAkZjRIeG9KbXRpS3VtSUZja3ZnVGZjZWN6UnV1TC44Z1BxZ1E4Tmw2bm1rQTZlby9pSWMvTHEiLCJfX3YiOjB9LCJpYXQiOjE2MTYwMzcyNzl9.qzWZgvQqkLmKTjAk1-g6ilexGsWCy4f3cImnQAG88vk
